### ISSUE TITLE
[Question] Will this mod bring performance improvement?

### ISSUE THREAD

**Issue by Rad586** [SteveKunG/FishNoStuck#1]
According its description, this mod seems to bring performance improvement, but I'm not quite sure...

**Comment by SteveKunG** [comment]
I've not tested yet, but it should affect mainly gameplay and fish mob behavior.

**Comment by SteveKunG** [comment]
I've tested using Spark. It's seems has no effect on the game performance.

For those who want to see profilers. Here is the results.
https://spark.lucko.me/ftaYGHUJVX
https://spark.lucko.me/acvXvoV4m2
