### ISSUE TITLE
สามารถ นำ แนวคิด มาทำเป็น server plugin ได้หรือไม่

### ISSUE THREAD

**Issue by nyaruru1** [SteveKunG/FishNoStuck#2]
ฉันไม่มี เซิฟเวอร์ที่ มีประสิทธิภาพเพียงพอที่จะใช้งาน fabricmc  อย่างราบรื่น

และฉันใช้ papermc อยู่ ฉันสามาถในแนวคิด(หรือโคดบางส่วน มาเพื่อแก้ไข "FishNoStuck"
ใน papermc server ได้หรือไม่

**Comment by SteveKunG** [comment]
ได้ครับ Fork Repo ไปทำได้เลยครับ
