### ISSUE TITLE
Incompatibility with Neruina (and possibly Fish Of Thieves) causing a server crash

### ISSUE THREAD

**Issue by Tempest-5ky** [SteveKunG/FishNoStuck#3]
What it says on the tin! A fish from Fish Of Thieves was erroring, though seemingly due to this mod Neruina was unable to remove it.

Fabric 1.20.1
FishNoStuck v1.0.1
[Neruina](https://modrinth.com/mod/neruina) v1.3.0
[Fish of Thieves](https://modrinth.com/mod/fish-of-thieves) v0.3.4

Crashlog: https://mclo.gs/ZcEwHbn

I have also reported this issue to Neruina.

**Comment by Tempest-5ky** [comment]
Fixed on Neruina's end https://github.com/Bawnorton/Neruina/issues/47#issuecomment-1974953206

**Comment by SteveKunG** [comment]
Hello, I haven't published a fix for null leader yet. I'll release a new version as soon as possible!

**Comment by SteveKunG** [comment]
1.0.2 has been released with a fix for null leader!
