### ISSUE TITLE
Tag mod as 1.21.1 compatible

### ISSUE THREAD

**Issue by anoomolu** [SteveKunG/FishNoStuck#5]
Hiya. Firstly wanted to say thank you for making this, entity fish are cool but without your fixes, they can be pretty derpy.

I was wondering if you'd be willing to tag the mod as 1.21.1 compatible (or 1.21.x if it also works on newer versions, which I'm pretty sure it should given fish movement wasn't really touched)? This way, mod managers like Prism can find the mod more easily. Cheers.

edit: I suppose this also applies to Squid No Glitch, although a few of the bugs were fixed in vanilla releases.

**Comment by SteveKunG** [comment]
Hey, thanks for notice me! The mod is working perfectly fine on 1.21.1+. And I already pushed a new version on both platforms.
Squid No Glitch needs to update a little bit more and I need to make sure it doesn't break on 1.21.3.
